spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pensieve
    username: postgres
    password: Password123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true

  # Application configuration
  application:
    name: pensieve

# Server configuration
server:
  port: 8080

